// Code generated by "enumer -type ValueID -output values_enumer.go"; DO NOT EDIT.

package sunny

import (
	"fmt"
	"strings"
)

const _ValueIDName = "ActivePowerMaxActivePowerMinusActivePowerMinusL1ActivePowerMinusL2ActivePowerMinusL3ActivePowerPlusActivePowerPlusL1ActivePowerPlusL2ActivePowerPlusL3ApparentPowerMinusApparentPowerMinusL1ApparentPowerMinusL2ApparentPowerMinusL3ApparentPowerPlusApparentPowerPlusL1ApparentPowerPlusL2ApparentPowerPlusL3ReactivePowerMinusReactivePowerMinusL1ReactivePowerMinusL2ReactivePowerMinusL3ReactivePowerPlusReactivePowerPlusL1ReactivePowerPlusL2ReactivePowerPlusL3PowerS1PowerS2PowerFactorPowerFactorL1PowerFactorL2PowerFactorL3ActiveEnergyMinusActiveEnergyMinusL1ActiveEnergyMinusL2ActiveEnergyMinusL3ActiveEnergyPlusActiveEnergyPlusL1ActiveEnergyPlusL2ActiveEnergyPlusL3ActiveEnergyPlusTodayApparentEnergyMinusApparentEnergyMinusL1ApparentEnergyMinusL2ApparentEnergyMinusL3ApparentEnergyPlusApparentEnergyPlusL1ApparentEnergyPlusL2ApparentEnergyPlusL3ReactiveEnergyMinusReactiveEnergyMinusL1ReactiveEnergyMinusL2ReactiveEnergyMinusL3ReactiveEnergyPlusReactiveEnergyPlusL1ReactiveEnergyPlusL2ReactiveEnergyPlusL3CurrentL1CurrentL2CurrentL3CurrentS1CurrentS2VoltageL1VoltageL2VoltageL3VoltageS1VoltageS2TimeFeedTimeOperatingUtilityFrequencyBatteryChargeBatteryTemperatureDeviceClassDeviceGridRelayDeviceNameDeviceStatusDeviceTemperatureDeviceTypeSoftwareVersion"

var _ValueIDIndex = [...]uint16{0, 14, 30, 48, 66, 84, 99, 116, 133, 150, 168, 188, 208, 228, 245, 264, 283, 302, 320, 340, 360, 380, 397, 416, 435, 454, 461, 468, 479, 492, 505, 518, 535, 554, 573, 592, 608, 626, 644, 662, 683, 702, 723, 744, 765, 783, 803, 823, 843, 862, 883, 904, 925, 943, 963, 983, 1003, 1012, 1021, 1030, 1039, 1048, 1057, 1066, 1075, 1084, 1093, 1101, 1114, 1130, 1143, 1161, 1172, 1187, 1197, 1209, 1226, 1236, 1251}

const _ValueIDLowerName = "activepowermaxactivepowerminusactivepowerminusl1activepowerminusl2activepowerminusl3activepowerplusactivepowerplusl1activepowerplusl2activepowerplusl3apparentpowerminusapparentpowerminusl1apparentpowerminusl2apparentpowerminusl3apparentpowerplusapparentpowerplusl1apparentpowerplusl2apparentpowerplusl3reactivepowerminusreactivepowerminusl1reactivepowerminusl2reactivepowerminusl3reactivepowerplusreactivepowerplusl1reactivepowerplusl2reactivepowerplusl3powers1powers2powerfactorpowerfactorl1powerfactorl2powerfactorl3activeenergyminusactiveenergyminusl1activeenergyminusl2activeenergyminusl3activeenergyplusactiveenergyplusl1activeenergyplusl2activeenergyplusl3activeenergyplustodayapparentenergyminusapparentenergyminusl1apparentenergyminusl2apparentenergyminusl3apparentenergyplusapparentenergyplusl1apparentenergyplusl2apparentenergyplusl3reactiveenergyminusreactiveenergyminusl1reactiveenergyminusl2reactiveenergyminusl3reactiveenergyplusreactiveenergyplusl1reactiveenergyplusl2reactiveenergyplusl3currentl1currentl2currentl3currents1currents2voltagel1voltagel2voltagel3voltages1voltages2timefeedtimeoperatingutilityfrequencybatterychargebatterytemperaturedeviceclassdevicegridrelaydevicenamedevicestatusdevicetemperaturedevicetypesoftwareversion"

func (i ValueID) String() string {
	i -= 1
	if i < 0 || i >= ValueID(len(_ValueIDIndex)-1) {
		return fmt.Sprintf("ValueID(%d)", i+1)
	}
	return _ValueIDName[_ValueIDIndex[i]:_ValueIDIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ValueIDNoOp() {
	var x [1]struct{}
	_ = x[ActivePowerMax-(1)]
	_ = x[ActivePowerMinus-(2)]
	_ = x[ActivePowerMinusL1-(3)]
	_ = x[ActivePowerMinusL2-(4)]
	_ = x[ActivePowerMinusL3-(5)]
	_ = x[ActivePowerPlus-(6)]
	_ = x[ActivePowerPlusL1-(7)]
	_ = x[ActivePowerPlusL2-(8)]
	_ = x[ActivePowerPlusL3-(9)]
	_ = x[ApparentPowerMinus-(10)]
	_ = x[ApparentPowerMinusL1-(11)]
	_ = x[ApparentPowerMinusL2-(12)]
	_ = x[ApparentPowerMinusL3-(13)]
	_ = x[ApparentPowerPlus-(14)]
	_ = x[ApparentPowerPlusL1-(15)]
	_ = x[ApparentPowerPlusL2-(16)]
	_ = x[ApparentPowerPlusL3-(17)]
	_ = x[ReactivePowerMinus-(18)]
	_ = x[ReactivePowerMinusL1-(19)]
	_ = x[ReactivePowerMinusL2-(20)]
	_ = x[ReactivePowerMinusL3-(21)]
	_ = x[ReactivePowerPlus-(22)]
	_ = x[ReactivePowerPlusL1-(23)]
	_ = x[ReactivePowerPlusL2-(24)]
	_ = x[ReactivePowerPlusL3-(25)]
	_ = x[PowerS1-(26)]
	_ = x[PowerS2-(27)]
	_ = x[PowerFactor-(28)]
	_ = x[PowerFactorL1-(29)]
	_ = x[PowerFactorL2-(30)]
	_ = x[PowerFactorL3-(31)]
	_ = x[ActiveEnergyMinus-(32)]
	_ = x[ActiveEnergyMinusL1-(33)]
	_ = x[ActiveEnergyMinusL2-(34)]
	_ = x[ActiveEnergyMinusL3-(35)]
	_ = x[ActiveEnergyPlus-(36)]
	_ = x[ActiveEnergyPlusL1-(37)]
	_ = x[ActiveEnergyPlusL2-(38)]
	_ = x[ActiveEnergyPlusL3-(39)]
	_ = x[ActiveEnergyPlusToday-(40)]
	_ = x[ApparentEnergyMinus-(41)]
	_ = x[ApparentEnergyMinusL1-(42)]
	_ = x[ApparentEnergyMinusL2-(43)]
	_ = x[ApparentEnergyMinusL3-(44)]
	_ = x[ApparentEnergyPlus-(45)]
	_ = x[ApparentEnergyPlusL1-(46)]
	_ = x[ApparentEnergyPlusL2-(47)]
	_ = x[ApparentEnergyPlusL3-(48)]
	_ = x[ReactiveEnergyMinus-(49)]
	_ = x[ReactiveEnergyMinusL1-(50)]
	_ = x[ReactiveEnergyMinusL2-(51)]
	_ = x[ReactiveEnergyMinusL3-(52)]
	_ = x[ReactiveEnergyPlus-(53)]
	_ = x[ReactiveEnergyPlusL1-(54)]
	_ = x[ReactiveEnergyPlusL2-(55)]
	_ = x[ReactiveEnergyPlusL3-(56)]
	_ = x[CurrentL1-(57)]
	_ = x[CurrentL2-(58)]
	_ = x[CurrentL3-(59)]
	_ = x[CurrentS1-(60)]
	_ = x[CurrentS2-(61)]
	_ = x[VoltageL1-(62)]
	_ = x[VoltageL2-(63)]
	_ = x[VoltageL3-(64)]
	_ = x[VoltageS1-(65)]
	_ = x[VoltageS2-(66)]
	_ = x[TimeFeed-(67)]
	_ = x[TimeOperating-(68)]
	_ = x[UtilityFrequency-(69)]
	_ = x[BatteryCharge-(70)]
	_ = x[BatteryTemperature-(71)]
	_ = x[DeviceClass-(72)]
	_ = x[DeviceGridRelay-(73)]
	_ = x[DeviceName-(74)]
	_ = x[DeviceStatus-(75)]
	_ = x[DeviceTemperature-(76)]
	_ = x[DeviceType-(77)]
	_ = x[SoftwareVersion-(78)]
}

var _ValueIDValues = []ValueID{ActivePowerMax, ActivePowerMinus, ActivePowerMinusL1, ActivePowerMinusL2, ActivePowerMinusL3, ActivePowerPlus, ActivePowerPlusL1, ActivePowerPlusL2, ActivePowerPlusL3, ApparentPowerMinus, ApparentPowerMinusL1, ApparentPowerMinusL2, ApparentPowerMinusL3, ApparentPowerPlus, ApparentPowerPlusL1, ApparentPowerPlusL2, ApparentPowerPlusL3, ReactivePowerMinus, ReactivePowerMinusL1, ReactivePowerMinusL2, ReactivePowerMinusL3, ReactivePowerPlus, ReactivePowerPlusL1, ReactivePowerPlusL2, ReactivePowerPlusL3, PowerS1, PowerS2, PowerFactor, PowerFactorL1, PowerFactorL2, PowerFactorL3, ActiveEnergyMinus, ActiveEnergyMinusL1, ActiveEnergyMinusL2, ActiveEnergyMinusL3, ActiveEnergyPlus, ActiveEnergyPlusL1, ActiveEnergyPlusL2, ActiveEnergyPlusL3, ActiveEnergyPlusToday, ApparentEnergyMinus, ApparentEnergyMinusL1, ApparentEnergyMinusL2, ApparentEnergyMinusL3, ApparentEnergyPlus, ApparentEnergyPlusL1, ApparentEnergyPlusL2, ApparentEnergyPlusL3, ReactiveEnergyMinus, ReactiveEnergyMinusL1, ReactiveEnergyMinusL2, ReactiveEnergyMinusL3, ReactiveEnergyPlus, ReactiveEnergyPlusL1, ReactiveEnergyPlusL2, ReactiveEnergyPlusL3, CurrentL1, CurrentL2, CurrentL3, CurrentS1, CurrentS2, VoltageL1, VoltageL2, VoltageL3, VoltageS1, VoltageS2, TimeFeed, TimeOperating, UtilityFrequency, BatteryCharge, BatteryTemperature, DeviceClass, DeviceGridRelay, DeviceName, DeviceStatus, DeviceTemperature, DeviceType, SoftwareVersion}

var _ValueIDNameToValueMap = map[string]ValueID{
	_ValueIDName[0:14]:           ActivePowerMax,
	_ValueIDLowerName[0:14]:      ActivePowerMax,
	_ValueIDName[14:30]:          ActivePowerMinus,
	_ValueIDLowerName[14:30]:     ActivePowerMinus,
	_ValueIDName[30:48]:          ActivePowerMinusL1,
	_ValueIDLowerName[30:48]:     ActivePowerMinusL1,
	_ValueIDName[48:66]:          ActivePowerMinusL2,
	_ValueIDLowerName[48:66]:     ActivePowerMinusL2,
	_ValueIDName[66:84]:          ActivePowerMinusL3,
	_ValueIDLowerName[66:84]:     ActivePowerMinusL3,
	_ValueIDName[84:99]:          ActivePowerPlus,
	_ValueIDLowerName[84:99]:     ActivePowerPlus,
	_ValueIDName[99:116]:         ActivePowerPlusL1,
	_ValueIDLowerName[99:116]:    ActivePowerPlusL1,
	_ValueIDName[116:133]:        ActivePowerPlusL2,
	_ValueIDLowerName[116:133]:   ActivePowerPlusL2,
	_ValueIDName[133:150]:        ActivePowerPlusL3,
	_ValueIDLowerName[133:150]:   ActivePowerPlusL3,
	_ValueIDName[150:168]:        ApparentPowerMinus,
	_ValueIDLowerName[150:168]:   ApparentPowerMinus,
	_ValueIDName[168:188]:        ApparentPowerMinusL1,
	_ValueIDLowerName[168:188]:   ApparentPowerMinusL1,
	_ValueIDName[188:208]:        ApparentPowerMinusL2,
	_ValueIDLowerName[188:208]:   ApparentPowerMinusL2,
	_ValueIDName[208:228]:        ApparentPowerMinusL3,
	_ValueIDLowerName[208:228]:   ApparentPowerMinusL3,
	_ValueIDName[228:245]:        ApparentPowerPlus,
	_ValueIDLowerName[228:245]:   ApparentPowerPlus,
	_ValueIDName[245:264]:        ApparentPowerPlusL1,
	_ValueIDLowerName[245:264]:   ApparentPowerPlusL1,
	_ValueIDName[264:283]:        ApparentPowerPlusL2,
	_ValueIDLowerName[264:283]:   ApparentPowerPlusL2,
	_ValueIDName[283:302]:        ApparentPowerPlusL3,
	_ValueIDLowerName[283:302]:   ApparentPowerPlusL3,
	_ValueIDName[302:320]:        ReactivePowerMinus,
	_ValueIDLowerName[302:320]:   ReactivePowerMinus,
	_ValueIDName[320:340]:        ReactivePowerMinusL1,
	_ValueIDLowerName[320:340]:   ReactivePowerMinusL1,
	_ValueIDName[340:360]:        ReactivePowerMinusL2,
	_ValueIDLowerName[340:360]:   ReactivePowerMinusL2,
	_ValueIDName[360:380]:        ReactivePowerMinusL3,
	_ValueIDLowerName[360:380]:   ReactivePowerMinusL3,
	_ValueIDName[380:397]:        ReactivePowerPlus,
	_ValueIDLowerName[380:397]:   ReactivePowerPlus,
	_ValueIDName[397:416]:        ReactivePowerPlusL1,
	_ValueIDLowerName[397:416]:   ReactivePowerPlusL1,
	_ValueIDName[416:435]:        ReactivePowerPlusL2,
	_ValueIDLowerName[416:435]:   ReactivePowerPlusL2,
	_ValueIDName[435:454]:        ReactivePowerPlusL3,
	_ValueIDLowerName[435:454]:   ReactivePowerPlusL3,
	_ValueIDName[454:461]:        PowerS1,
	_ValueIDLowerName[454:461]:   PowerS1,
	_ValueIDName[461:468]:        PowerS2,
	_ValueIDLowerName[461:468]:   PowerS2,
	_ValueIDName[468:479]:        PowerFactor,
	_ValueIDLowerName[468:479]:   PowerFactor,
	_ValueIDName[479:492]:        PowerFactorL1,
	_ValueIDLowerName[479:492]:   PowerFactorL1,
	_ValueIDName[492:505]:        PowerFactorL2,
	_ValueIDLowerName[492:505]:   PowerFactorL2,
	_ValueIDName[505:518]:        PowerFactorL3,
	_ValueIDLowerName[505:518]:   PowerFactorL3,
	_ValueIDName[518:535]:        ActiveEnergyMinus,
	_ValueIDLowerName[518:535]:   ActiveEnergyMinus,
	_ValueIDName[535:554]:        ActiveEnergyMinusL1,
	_ValueIDLowerName[535:554]:   ActiveEnergyMinusL1,
	_ValueIDName[554:573]:        ActiveEnergyMinusL2,
	_ValueIDLowerName[554:573]:   ActiveEnergyMinusL2,
	_ValueIDName[573:592]:        ActiveEnergyMinusL3,
	_ValueIDLowerName[573:592]:   ActiveEnergyMinusL3,
	_ValueIDName[592:608]:        ActiveEnergyPlus,
	_ValueIDLowerName[592:608]:   ActiveEnergyPlus,
	_ValueIDName[608:626]:        ActiveEnergyPlusL1,
	_ValueIDLowerName[608:626]:   ActiveEnergyPlusL1,
	_ValueIDName[626:644]:        ActiveEnergyPlusL2,
	_ValueIDLowerName[626:644]:   ActiveEnergyPlusL2,
	_ValueIDName[644:662]:        ActiveEnergyPlusL3,
	_ValueIDLowerName[644:662]:   ActiveEnergyPlusL3,
	_ValueIDName[662:683]:        ActiveEnergyPlusToday,
	_ValueIDLowerName[662:683]:   ActiveEnergyPlusToday,
	_ValueIDName[683:702]:        ApparentEnergyMinus,
	_ValueIDLowerName[683:702]:   ApparentEnergyMinus,
	_ValueIDName[702:723]:        ApparentEnergyMinusL1,
	_ValueIDLowerName[702:723]:   ApparentEnergyMinusL1,
	_ValueIDName[723:744]:        ApparentEnergyMinusL2,
	_ValueIDLowerName[723:744]:   ApparentEnergyMinusL2,
	_ValueIDName[744:765]:        ApparentEnergyMinusL3,
	_ValueIDLowerName[744:765]:   ApparentEnergyMinusL3,
	_ValueIDName[765:783]:        ApparentEnergyPlus,
	_ValueIDLowerName[765:783]:   ApparentEnergyPlus,
	_ValueIDName[783:803]:        ApparentEnergyPlusL1,
	_ValueIDLowerName[783:803]:   ApparentEnergyPlusL1,
	_ValueIDName[803:823]:        ApparentEnergyPlusL2,
	_ValueIDLowerName[803:823]:   ApparentEnergyPlusL2,
	_ValueIDName[823:843]:        ApparentEnergyPlusL3,
	_ValueIDLowerName[823:843]:   ApparentEnergyPlusL3,
	_ValueIDName[843:862]:        ReactiveEnergyMinus,
	_ValueIDLowerName[843:862]:   ReactiveEnergyMinus,
	_ValueIDName[862:883]:        ReactiveEnergyMinusL1,
	_ValueIDLowerName[862:883]:   ReactiveEnergyMinusL1,
	_ValueIDName[883:904]:        ReactiveEnergyMinusL2,
	_ValueIDLowerName[883:904]:   ReactiveEnergyMinusL2,
	_ValueIDName[904:925]:        ReactiveEnergyMinusL3,
	_ValueIDLowerName[904:925]:   ReactiveEnergyMinusL3,
	_ValueIDName[925:943]:        ReactiveEnergyPlus,
	_ValueIDLowerName[925:943]:   ReactiveEnergyPlus,
	_ValueIDName[943:963]:        ReactiveEnergyPlusL1,
	_ValueIDLowerName[943:963]:   ReactiveEnergyPlusL1,
	_ValueIDName[963:983]:        ReactiveEnergyPlusL2,
	_ValueIDLowerName[963:983]:   ReactiveEnergyPlusL2,
	_ValueIDName[983:1003]:       ReactiveEnergyPlusL3,
	_ValueIDLowerName[983:1003]:  ReactiveEnergyPlusL3,
	_ValueIDName[1003:1012]:      CurrentL1,
	_ValueIDLowerName[1003:1012]: CurrentL1,
	_ValueIDName[1012:1021]:      CurrentL2,
	_ValueIDLowerName[1012:1021]: CurrentL2,
	_ValueIDName[1021:1030]:      CurrentL3,
	_ValueIDLowerName[1021:1030]: CurrentL3,
	_ValueIDName[1030:1039]:      CurrentS1,
	_ValueIDLowerName[1030:1039]: CurrentS1,
	_ValueIDName[1039:1048]:      CurrentS2,
	_ValueIDLowerName[1039:1048]: CurrentS2,
	_ValueIDName[1048:1057]:      VoltageL1,
	_ValueIDLowerName[1048:1057]: VoltageL1,
	_ValueIDName[1057:1066]:      VoltageL2,
	_ValueIDLowerName[1057:1066]: VoltageL2,
	_ValueIDName[1066:1075]:      VoltageL3,
	_ValueIDLowerName[1066:1075]: VoltageL3,
	_ValueIDName[1075:1084]:      VoltageS1,
	_ValueIDLowerName[1075:1084]: VoltageS1,
	_ValueIDName[1084:1093]:      VoltageS2,
	_ValueIDLowerName[1084:1093]: VoltageS2,
	_ValueIDName[1093:1101]:      TimeFeed,
	_ValueIDLowerName[1093:1101]: TimeFeed,
	_ValueIDName[1101:1114]:      TimeOperating,
	_ValueIDLowerName[1101:1114]: TimeOperating,
	_ValueIDName[1114:1130]:      UtilityFrequency,
	_ValueIDLowerName[1114:1130]: UtilityFrequency,
	_ValueIDName[1130:1143]:      BatteryCharge,
	_ValueIDLowerName[1130:1143]: BatteryCharge,
	_ValueIDName[1143:1161]:      BatteryTemperature,
	_ValueIDLowerName[1143:1161]: BatteryTemperature,
	_ValueIDName[1161:1172]:      DeviceClass,
	_ValueIDLowerName[1161:1172]: DeviceClass,
	_ValueIDName[1172:1187]:      DeviceGridRelay,
	_ValueIDLowerName[1172:1187]: DeviceGridRelay,
	_ValueIDName[1187:1197]:      DeviceName,
	_ValueIDLowerName[1187:1197]: DeviceName,
	_ValueIDName[1197:1209]:      DeviceStatus,
	_ValueIDLowerName[1197:1209]: DeviceStatus,
	_ValueIDName[1209:1226]:      DeviceTemperature,
	_ValueIDLowerName[1209:1226]: DeviceTemperature,
	_ValueIDName[1226:1236]:      DeviceType,
	_ValueIDLowerName[1226:1236]: DeviceType,
	_ValueIDName[1236:1251]:      SoftwareVersion,
	_ValueIDLowerName[1236:1251]: SoftwareVersion,
}

var _ValueIDNames = []string{
	_ValueIDName[0:14],
	_ValueIDName[14:30],
	_ValueIDName[30:48],
	_ValueIDName[48:66],
	_ValueIDName[66:84],
	_ValueIDName[84:99],
	_ValueIDName[99:116],
	_ValueIDName[116:133],
	_ValueIDName[133:150],
	_ValueIDName[150:168],
	_ValueIDName[168:188],
	_ValueIDName[188:208],
	_ValueIDName[208:228],
	_ValueIDName[228:245],
	_ValueIDName[245:264],
	_ValueIDName[264:283],
	_ValueIDName[283:302],
	_ValueIDName[302:320],
	_ValueIDName[320:340],
	_ValueIDName[340:360],
	_ValueIDName[360:380],
	_ValueIDName[380:397],
	_ValueIDName[397:416],
	_ValueIDName[416:435],
	_ValueIDName[435:454],
	_ValueIDName[454:461],
	_ValueIDName[461:468],
	_ValueIDName[468:479],
	_ValueIDName[479:492],
	_ValueIDName[492:505],
	_ValueIDName[505:518],
	_ValueIDName[518:535],
	_ValueIDName[535:554],
	_ValueIDName[554:573],
	_ValueIDName[573:592],
	_ValueIDName[592:608],
	_ValueIDName[608:626],
	_ValueIDName[626:644],
	_ValueIDName[644:662],
	_ValueIDName[662:683],
	_ValueIDName[683:702],
	_ValueIDName[702:723],
	_ValueIDName[723:744],
	_ValueIDName[744:765],
	_ValueIDName[765:783],
	_ValueIDName[783:803],
	_ValueIDName[803:823],
	_ValueIDName[823:843],
	_ValueIDName[843:862],
	_ValueIDName[862:883],
	_ValueIDName[883:904],
	_ValueIDName[904:925],
	_ValueIDName[925:943],
	_ValueIDName[943:963],
	_ValueIDName[963:983],
	_ValueIDName[983:1003],
	_ValueIDName[1003:1012],
	_ValueIDName[1012:1021],
	_ValueIDName[1021:1030],
	_ValueIDName[1030:1039],
	_ValueIDName[1039:1048],
	_ValueIDName[1048:1057],
	_ValueIDName[1057:1066],
	_ValueIDName[1066:1075],
	_ValueIDName[1075:1084],
	_ValueIDName[1084:1093],
	_ValueIDName[1093:1101],
	_ValueIDName[1101:1114],
	_ValueIDName[1114:1130],
	_ValueIDName[1130:1143],
	_ValueIDName[1143:1161],
	_ValueIDName[1161:1172],
	_ValueIDName[1172:1187],
	_ValueIDName[1187:1197],
	_ValueIDName[1197:1209],
	_ValueIDName[1209:1226],
	_ValueIDName[1226:1236],
	_ValueIDName[1236:1251],
}

// ValueIDString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ValueIDString(s string) (ValueID, error) {
	if val, ok := _ValueIDNameToValueMap[s]; ok {
		return val, nil
	}
	s = strings.ToLower(s)
	if val, ok := _ValueIDNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ValueID values", s)
}

// ValueIDValues returns all values of the enum
func ValueIDValues() []ValueID {
	return _ValueIDValues
}

// ValueIDStrings returns a slice of all String values of the enum
func ValueIDStrings() []string {
	strs := make([]string, len(_ValueIDNames))
	copy(strs, _ValueIDNames)
	return strs
}

// IsAValueID returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ValueID) IsAValueID() bool {
	for _, v := range _ValueIDValues {
		if i == v {
			return true
		}
	}
	return false
}
